### ISSUE TITLE
Validate & Replace Hash

### ISSUE THREAD

**Issue by ChrisMcKee** [BcryptNet/bcrypt.net#1]
Possible impl
- Takes hash & pass & new workload size
- Verifies 
- Creates New Hash if valid & workload is larger then present
- Returns replacement hash

**Comment by ChrisMcKee** [comment]
Hi @Drenskin 
This was 'completed' via the validate and replace password method.

```csharp
public static string ValidateAndReplacePassword(string currentKey, string currentHash, bool currentKeyEnhancedEntropy, HashType oldHashType,
 string newKey, bool newKeyEnhancedEntropy = false, HashType newHashType = DefaultEnhancedHashType, int workFactor = DefaultRounds, bool forceWorkFactor = false)
```
In the case of this method you can set a workFactor greater than the original hash to upgrade it (falls back to using the default rounds or the work factor of the hash depending on which is greater if not set). 

I can see what you mean though and following a normal .net pattern I could add a method that would return `bool` but out `hash`. 
`ValidateAndUpgrade` ... something like that; naming is a bitch.

**Comment by Drenskin** [comment]
Thank you for your response.

I read the method ValidateAndReplacePassword, but it is specifically built to replace the password. If in my case I want to keep the same password (before hash), but increase the work factor if needed, and I call this method with the same password in currentKey & newKey, it will compute 2 identical hash for no apparent reason : 1 for the verify and 1 for the HashPassword even if the workFactor hasn't increased.

**Comment by ChrisMcKee** [comment]
Yep def not the same use case; I'll flesh it out.

**Comment by ChrisMcKee** [comment]
At the moment (without this being a built in method) the flow is as follows

```
const int myHashLevel 13
if PasswordNeedsRehash(hash, myHashLevel)
  newhash =  ValidateAndReplacePassword
  code to store new pass
else
  Verify
```
  
I'm considering 

```
bool ValidateAndUpgrade(out string hash, string currentKey, string currentHash, int workFactor = DefaultRounds, bool forceWorkFactor = false)
```

But you'd be still left with the final comparison (unless it has an out of changed which starts to look messy)

**Comment by Drenskin** [comment]
What about
```
bool ValidateAndUpgrade(string currentKey, string currentHash, int workFactor = DefaultRounds, bool forceWorkFactor = false, out string newHash)
```
where newHash is only filled if the hash has been upgraded.
Or
```
bool ValidateAndUpgrade(string currentKey, string currentHash, int workFactor = DefaultRounds, bool forceWorkFactor = false, out bool hashUpgraded, out string newHash)
```
with hashUpgraded that tells us directly that the hash has been upgraded (and that we need to save it).

Otherwise, if you don't want out parameters, we can also do :
```
(bool Verified, bool HashUpgraded, bool NewHash) ValidateAndUpgrade(string currentKey, string currentHash, int workFactor = DefaultRounds, bool forceWorkFactor = false)
```
but I personnaly find this even less readable.

Another suggestion, just add to Verify at the end an `out int workFactor` ? It is simple and would enabled us to just do this :
```
const int myHashLevel 13
if Verify(test, hash, out int workFactor)
{
    if (workFactor < myHashLevel)
        newhash =  HashPassword
}
```

**Comment by ChrisMcKee** [comment]
```
        public void ValidatePasswordsInMyApp()
        {
           // These are just here rather than params and so its obvious the workloads lower
            var passToUse = "aiehfaeipfhaeipfhaeipfhaeipfhaeipfhea";
            var hashToUse = BCrypt.HashPassword(passToUse, 8);

            var hashTuple = ValidateHash(hashToUse, passToUse);

            if (!hashTuple.isValid) /* Return false/throw error whatever your app does to handle auth failure*/ return;
            if (hashTuple.newHash != "")
            {
                // store change.
            }
            // then return true / return to pass next step in pipeline or whatever.
        }

        private const int AppWorkLoad = 12;

        public static (bool isValid, string newHash) ValidateHash(string hash, string password)
        {
            if (BCrypt.Verify(password, hash))
            {
                if (BCrypt.PasswordNeedsRehash(hash, AppWorkLoad))
                {
                    return (true, BCrypt.HashPassword(password, AppWorkLoad));
                }
                return (true, string.Empty);
            }

            return (false, string.Empty);
        }
```

Using the current codebase you're current app can handle replacing hashes inline as above. 
As its simply one utility method and as the parsing of workload is more efficient now it seems the best way of handling it; I've used a tuple above, of course you can implement it as is best for your code base.
