### ISSUE TITLE
how to upgrade / replace old bcrypt with bcrypt.net

### ISSUE THREAD

**Issue by fasteddys** [BcryptNet/bcrypt.net#104]
hello, can you share some guidance, several functions are missing.

**Comment by ChrisMcKee** [comment]
The library is backward compatible; what is it you're trying to use that you cant find?

**Comment by fasteddys** [comment]
I upgraded two asp projects and they no longer worked unless I updated the Bcrypt libs, and many of the functions were incompatible.

ASP 4.5 to `ASP 4.8` (failed with updated to latest nugets for bcrupt ref)

`dtonettool Upgrad-Assitant` ASP 4.5 to `ASP core 6 `(failed with updated to latest nugets for bcrupt ref)

**Comment by ChrisMcKee** [comment]
Which methods, and how were they incompatible?
Was it upgrading from bcrypt.net to next?
What versions of the library?

Give me a hint, I can't see your screen or guess.
