### ISSUE TITLE
Target .NET 6

### ISSUE THREAD

**Issue by maxime-ducoroy** [BcryptNet/bcrypt.net#106]
Hello,

Do you plan to support the .NET 6 version?

Thanks

**Comment by ChrisMcKee** [comment]
Yep the changes are in (looking at master) 
I got distracted 😂

It should all work as is in 6 anyway but YES i will push a 6 release
probably today before I forget

**Comment by maxime-ducoroy** [comment]
No worries 😃

It's all in the readme I read:

> v4.0.2 - Addition of .net 5 targeting; wrap shaxxx creation in using to release.

**Comment by ChrisMcKee** [comment]
Aye I got in the habit of adding the details in the tab https://github.com/BcryptNet/bcrypt.net/releases
The changelog way is more git-agnostic.  Old habits die hard

**Comment by ChrisMcKee** [comment]
Its out there now

https://www.nuget.org/packages/BCrypt.Net-Next/4.0.3

**Comment by maxime-ducoroy** [comment]
You are great, thanks 😃
