### ISSUE TITLE
Namespace and Class name conflict

### ISSUE THREAD

**Issue by evileyecc1** [BcryptNet/bcrypt.net#11]
```
using System;
using bcrypt = BCrypt.Net.BCrypt;

namespace ChatServer
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(bcrypt.Verify("123456", "$2y$10$3Li1pWPdcGTRnZHeNtCR1OPseHtXVL9TdomRaIaXaeB/xS0vgoEJ."));
        }
    }
}
```
Sorry for my bad english.I need to renmae the Bcrypt class and use it.
If i use it like this
```
using System;
using BCrypt.Net;

namespace ChatServer
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(Bcrypt.Verify("123456", "$2y$10$3Li1pWPdcGTRnZHeNtCR1OPseHtXVL9TdomRaIaXaeB/xS0vgoEJ."));
        }
    }
}

```
I will get error Bcrypt is a namespace and do not have Verify function.

**Comment by ChrisMcKee** [comment]
Hi, that doesn't sound right. 
Take a look at https://github.com/BcryptNet/bcrypt.net/blob/master/IntegrationTest/TestVariousVersionsOfDotNet/DotNetCore/Program.cs

Your code should work... bar the Verify call in the code you pasted above having a lowercase C (its BCrypt not Bcrypt) 

![image](https://user-images.githubusercontent.com/83597/30539109-d9db2c76-9c68-11e7-8020-7e738690eb62.png)
![image](https://user-images.githubusercontent.com/83597/30539139-f1c9f704-9c68-11e7-8c32-a435fc46e312.png)

I've pasted your code into mine (bar the minor correction to casing)

![image](https://user-images.githubusercontent.com/83597/30539186-29a609e2-9c69-11e7-9211-ac064454fc09.png)




I was constrained on the namespace as this was an existing library that had been abandoned and the aim was to make the necessary fixes and to enhance it.

**Comment by evileyecc1** [comment]
I try again.But only BCrypt namespace and no BCrypt Class.
Enviroment:Visual Studio 2017
![image](https://user-images.githubusercontent.com/22828359/30540780-3269d2f6-9cab-11e7-9df7-fb61fb32e06c.png)
I still can use it by `using bcrypt = BCrypt.Net.BCrypt;`
And I now know that it is a namespace that cannot be modified

**Comment by ChrisMcKee** [comment]
@evileyecc1 
ahh I see if the using statement is in the namespace it will function as expected. Outside of the namespace VS gets confused between the two references and you're left using `using crypt = BCrypt.Net.BCrypt;`

**Comment by evileyecc1** [comment]
OK.I understand what you mean.Thank for you reply
