### ISSUE TITLE
Is enhanced entropy mode vulnerable to password shucking?

### ISSUE THREAD

**Issue by lbras** [BcryptNet/bcrypt.net#110]
I read about password shucking in [OWASP Password Storage Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html) and then in [this article from Scott Brady](https://www.scottbrady91.com/authentication/beware-of-password-shucking).

From my understanding, pre-hashing should be ok if the pre-hash is salted. The following paragraph seems to imply the pre-hash is not salted:

> What does it do? We take the utf8 bytes of your password as inputBytes SHA hash them, convert to base64 (for compatibility with other language implementations) then use those bytes to perform the standard bcrypt call.

I assume salting the pre-hash would break compatibility with other language implementations?

In any case, if password shucking is a possibility, maybe the following should be amended:

> Should I use Enhanced Entropy? You lose nothing by using it

**Comment by ChrisMcKee** [comment]
I may add in more api; or I may simply document it. Its a hard choice.

**Comment by lbras** [comment]
@ChrisMcKee thanks a lot for your highly detailed answer and pointing out the real risk here: password reuse.

I couldn't find much information about password shucking other than warnings about its dangers from OWASP and other sources. It's nice to have a down to earth perspective on what's really at stake here.

Your answer properly documents it, I think. Anyone wanting to know more about password shucking will easily find it and if it really is a concern they can always do the pre-hashing themselves.

Thanks, once more, and sorry for the late reply - life happened (quite literally :blush:).
