### ISSUE TITLE
Question: Can I configure the Library to be compatible with Laravel bcrypt

### ISSUE THREAD

**Issue by QaisAlkhateeb** [BcryptNet/bcrypt.net#112]
I have an application built on Laravel and recently we migrate the data to .NET, I have list of users and their passwords hashed using `bcrypt` https://laravel.com/docs/5.0/hashing#basic-usage. 

When I'm using the `BCrypt.Net.BCrypt.Verify` it did not work, my question is there a way to configure the .NET implementation to be compatible with Laravel implementation ?

**Comment by ChrisMcKee** [comment]
It should just work. 
Older versions of laravel used aes https://laravel.com/docs/5.0/encryption rather than bcrypt by default; does the interrogate hash method work?

**Comment by QaisAlkhateeb** [comment]
Hi @ChrisMcKee  Thanks for your response, 

Here is an example of the password that I have:

 =============================================
- password:
123465
- passwordHashPhp:
$2y$10$UR64fXDeO63S2CsLC2Qsb.mMTGcySwehUWOkuasxmff1vvCMa9.yK
- passwordHashPhpWithA:
$2a$10$UR64fXDeO63S2CsLC2Qsb.mMTGcySwehUWOkuasxmff1vvCMa9.yK
- passwordHashNet:
$2a$10$/ZgbNLGxEHqJJskdFbhBx.xAHkQh4oRiRqYPUuILOlY9y.TGSylOG
- passwordHashPhpSaltReplaced:
$2y$10$/ZgbNLGxEHqJJskdFbhBx.mMTGcySwehUWOkuasxmff1vvCMa9.yK
- passwordHashPhpWithASaltReplaced:
$2a$10$/ZgbNLGxEHqJJskdFbhBx.mMTGcySwehUWOkuasxmff1vvCMa9.yK
verify passwordHashPhp: False
verify passwordHashPhpWithA: False
verify passwordHashPhpSaltReplaced: False
verify passwordHashPhpWithASaltReplaced: False
================================================

and here is the my code:

```csharp
static void Main(string[] args)
{
    var password = "123465";
    var passwordHashPhp = "$2y$10$UR64fXDeO63S2CsLC2Qsb.mMTGcySwehUWOkuasxmff1vvCMa9.yK";
    var passwordHashPhpWithA = "$2a$10$UR64fXDeO63S2CsLC2Qsb.mMTGcySwehUWOkuasxmff1vvCMa9.yK";
    var passwordHashNet = BCrypt.Net.BCrypt.HashPassword(password, 10);
    var phpSalt = passwordHashPhp.Substring(7, 22);
    var netSalt = passwordHashNet.Substring(7, 22);
    var passwordHashPhpSaltReplaced = passwordHashPhp.Replace(phpSalt, netSalt);
    var passwordHashPhpWithASaltReplaced = passwordHashPhpWithA.Replace(phpSalt, netSalt);

    Console.WriteLine("=============================================");
    Console.WriteLine($"- password: \n{password}");
    Console.WriteLine($"- passwordHashPhp: \n{passwordHashPhp}");
    Console.WriteLine($"- passwordHashPhpWithA: \n{passwordHashPhpWithA}");
    Console.WriteLine($"- passwordHashNet: \n{passwordHashNet}");
    Console.WriteLine($"- passwordHashPhpSaltReplaced: \n{passwordHashPhpSaltReplaced}");
    Console.WriteLine($"- passwordHashPhpWithASaltReplaced: \n{passwordHashPhpWithASaltReplaced}");

    Console.WriteLine($"verify passwordHasNet: {BCrypt.Net.BCrypt.Verify(password, passwordHashNet)}");
    Console.WriteLine($"verify passwordHashPhp: {BCrypt.Net.BCrypt.Verify(password, passwordHashPhp)}");
    Console.WriteLine($"verify passwordHashPhpWithA: {BCrypt.Net.BCrypt.Verify(password, passwordHashPhpWithA)}");
    Console.WriteLine($"verify passwordHashPhpSaltReplaced: {BCrypt.Net.BCrypt.Verify(password, passwordHashPhpSaltReplaced)}");
    Console.WriteLine($"verify passwordHashPhpWithASaltReplaced: {BCrypt.Net.BCrypt.Verify(password, passwordHashPhpWithASaltReplaced)}");

    Console.ReadLine();
}
```

**Comment by ChrisMcKee** [comment]
@QaisAlkhateeb did you work this out?
I was on holiday so I've not got around to prodding php via docker

**Comment by QaisAlkhateeb** [comment]
Thanks @ChrisMcKee, unfortunately it did not work, but currently I'm using another implementation and the issue solved.
Thanks for your support :)
