### ISSUE TITLE
Add support for some old platform

### ISSUE THREAD

**Issue by wherewhere** [BcryptNet/bcrypt.net#120]
Could you add netstandard 1.4 and netcore50 to support UWP and other old platform? UWP below rs3 only support netstandard 1.4. Since this project is support old .net version like 2.0. I think it is better to support more platforms.
https://github.com/Coolapk-UWP/Coolapk-Lite/tree/master/CoolapkLite%2FBCrypt.Net

**Comment by ChrisMcKee** [comment]
Thanks, good to know. 
One of the major downsides to nuget is you don't know what the codes being used in so that's helpful to know. 

I'll drop it into the next minor release once I've checked dotnets targeting matrix thingi to make sure.

**Comment by wherewhere** [comment]
Could I push a PR to add the netcore50 and netstandard1.4?

**Comment by ChrisMcKee** [comment]
It's not quite as simple as expected as netcore50 breaks in msbuild
https://github.com/dotnet/msbuild/issues/5833
Support was dropped.

I can add 1.4 without any real issue; going off https://learn.microsoft.com/en-us/nuget/reference/target-frameworks#portable-class-libraries for a post-pcl world 1.4 is the one to use.

---
> Since this project is support old .net version like 2.0. I think it is better to support more platforms.


v5 of this project will be dropping a lot of the supports; 4 will get maintenance updates after that. Microsofts version-splurge over the last 6 years has made it a mess to contain.

**Comment by wherewhere** [comment]
You need install windows 10 sdk to build netcore50.

**Comment by wherewhere** [comment]
Take a try https://github.com/wherewhere/bcrypt.net

**Comment by wherewhere** [comment]
So can I push my commit? 
(I remove the net5 and add netstandard1.4 netcore50 netcoreapp3.1 and update net4.8 to 4.8.1
(I also update old csproj to new sdk one...
