### ISSUE TITLE
Verify method returns false each time if its used inside the if statement

### ISSUE THREAD

**Issue by yugyesh** [BcryptNet/bcrypt.net#124]
- When I verify the password inside the if statement it fails
`if (BC.Verify(password, hashPassword))` 
- However, when I assign  the value of the method to a variable it works fine
`bool isValidUser = BC.Verify(password, hashPassword);
if (!isValidUser)`

- I am using .net 6 isolated azure functions.

**Comment by ChrisMcKee** [comment]
Is the first one a typo? Semicolon after verify in the if statement.
