### ISSUE TITLE
Support for pre-v3.5 enhanced hashes in 4.x 

### ISSUE THREAD

**Issue by jeroenbai** [BcryptNet/bcrypt.net#125]
We were upgrading from 3.2.1 to 4.0.3, and after reading isssue #79 we are now upgrading from 3.2.1 to 3.5 instead, plus using the suggested migration approach.

Now, after a successful login using the v3 hash, the users password is encrypted using v4CompatibleEnhancedEntropy and stored (migrated), so the next time they log in will have a login success using v4CompatibleEnhancedEntropy verify.

```
string passwordHash = BCrypt.HashPassword(password, BCrypt.GenerateSalt(), enhancedEntropy:true, v4CompatibleEnhancedEntropy:true);

bool success = BCrypt.Verify(password, storedPasswordHash, enhancedEntropy: true, v4CompatibleEnhancedEntropy: true);
```

Since we do need the plain password to do the migration, we cannot do a bulk migration for all users, using the v3 hashes, but we need the user to log in and then migrate that user.

This means, that we can only upgrade from 3.5 to 4.x as soon as all users have logged in once. Alternatively we could upgrade to 4.x after some time, and have users reset their password due to longer inactivity.

What are your thoughts about adding a v3CompatibleEnhancedEntropy argument to the Verify method, so v 4.x can still validate users with v3 password hashes?

**Comment by responsibleboy** [comment]
我也遇到这个问题了，不能升级到最新版本4.x，
3.5版本生成的hash值，在4.0.3版本中验证不通过，
EnhancedHashPassword("kycx123456")

**Comment by jeroenbai** [comment]
@responsibleboy "The hash value generated by version 3.5 failed the verification in version 4.0.3.
EnhancedHashPassword("kycx123456")"

In 3.5, you have to hash passwords using 

`string passwordHash = BCrypt.HashPassword(password, BCrypt.GenerateSalt(), enhancedEntropy:true, v4CompatibleEnhancedEntropy:true);
`
See https://github.com/BcryptNet/bcrypt.net/issues/79#issuecomment-730470506

If you want to migrate
The easiest way to migrate the prior hashes is to store a flag against the user or set a before date check in the hash check based on the users auth records last modified.

The laziest way / simplest way to handle the difference would be to use v3.5.0 (which has the additional v4CompatibleEnhancedEntropy flag); (Laziest way because it reduces the need to manage state)

Authenticate the user using v4 compatible;
if/when hash fails to validate using standard v3 logic
if valid at this point rehash against with v4 compatibility and store.

**Comment by jeroenbai** [comment]
Regarding my initial reason for this issue: we will postpone upgrading to 4.0, and when we do upgrade from 3.5 to 4.0, the users that have not logged in sincee the 3.5 go live, will need to reset their password "inactive for too long".

**Comment by ChrisMcKee** [comment]
> Regarding my initial reason for this issue: we will work around this, by postponing the upgrade to 4.0, and when we do upgrade from 3.5 to 4.0, the users that have not logged in since the 3.5 go live, will need to reset their password "inactive for too long". 

It's a good pattern; it's usually a good idea to push mail to inactive accounts after an appropriate period (appropriate for the account type e.g. insurance usually being any account unused in 13 months) and either removing or locking old accounts; in the case of locking using that flag to force them through a password reset email.
It adds a bit of extra protection in that you reduce the chance of stolen creds giving away access to an account that isn't used often.
