### ISSUE TITLE
Silly question - why not provide the salt?

### ISSUE THREAD

**Issue by davidkeaveny** [BcryptNet/bcrypt.net#14]
As the issue title says, why does the documentation recommend that you let the BCrypt software provided the salt, rather than providing your own?

**Comment by ChrisMcKee** [comment]
I'll close this as a ticket; but if you've anything further I'll still get the notifications 👍

**Comment by davidkeaveny** [comment]
OK, thanks, that's much clearer; I'll leave BCrypt to do things as it thinks best!
