### ISSUE TITLE
Enhanced Entropy: sha384 and NUL bytes

### ISSUE THREAD

**Issue by Indigo744** [BcryptNet/bcrypt.net#15]
Hello,

I was reading [this article](https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016#why-bcrypt) (which actually recommend this library) about using bcrypt for password hashing.

It suggests to pass the password through SHA384 before using bcrypt in order to circumvent the bcrypt limitation.

I was glad to find that your library implemented it through the `enhancedEntropy` parameter.

However, [looking at the code](https://github.com/BcryptNet/bcrypt.net/blob/master/src/BCrypt.Net/BCrypt.cs#L596), I couldn't find any mention of base64 encoding after the SHA384 and prior bcrypt.

base64 is suggested in the article because:
> Bcrypt truncates on NUL bytes.

And 

> A base64-encoded hash is guaranteed to not contain NUL bytes

Thanks for your insight.

**EDIT** Adding some reference implementation seen elsewhere:
In [PasswordLock PHP library](https://github.com/paragonie/password_lock), they [effectively perform](https://github.com/paragonie/password_lock/blob/master/src/PasswordLock.php#L25) base64 after sha384.
In [passlib Python library](https://pypi.org/project/passlib/), they [also perform](http://passlib.readthedocs.io/en/stable/lib/passlib.hash.bcrypt_sha256.html) base64 after sha256.

**Comment by ChrisMcKee** [comment]
I'll take a look in a bit, I've looked into this before, there's a test around null byte in strings. 

Didn't realise @paragonie-scott had linked it.

**Comment by Indigo744** [comment]
Well, the NULL char is actually not related to the fact that the password can contain a NULL char, but instead the the sha384 function can return a string containing a NULL char.

I'm trying to find an article I came across where it gave some example.

**Comment by ChrisMcKee** [comment]
I'm aware of the why, I was trying to avoid a rambling answer. 
If the HMAC passes a null value along the resultant byte array would be the same as passing any other byte array containing a null. The existing code handles null bytes as part of meeting the 2a standard which added. 

```
* the string must be UTF-8 encoded
* the null terminator must be included
```

**Comment by ChrisMcKee** [comment]
Just to show it at a lower level; 
![image](https://user-images.githubusercontent.com/83597/39452129-1126ebb4-4cc9-11e8-8867-4a18b8f6fe9c.png)
I don't push the crypt-raw test as the method is private; as is decode. I may add them and change private to internal so the tests can access those areas of the method.

You'll probably find this interesting also https://blog.ircmaxell.com/2015/03/security-issue-combining-bcrypt-with.html < most annoying part about this implementation but of course being that it was at the module level so pretty ubiquitous.

**Comment by Indigo744** [comment]
Since you are adding sha512, maybe also add an option to add sha256 for interoperability with other lib (such as Passlib)? I don't know if it's worth it actually...

Anyway, I'm glad we were able to work things out and that everything is OK and secure :smile: 
Thanks for actively maintaining this lib. You're doing an awesome job.

**Comment by Indigo744** [comment]
Oh, I just noticed that [Passlib uses a specific algorithm](http://passlib.readthedocs.io/en/stable/lib/passlib.hash.bcrypt_sha256.html#format) name in the crypt format: `$bcrypt-sha256$`

A quick search tells me they are the only one doing it (I may be wrong tho). However, it looks interesting, since it clearly explains the underlying algorithm.

**Comment by ChrisMcKee** [comment]
@Indigo744 suprised the didnt go with the 2a-sha2 but as it stands I think they ditched the Modular Crypto Format for PHF (https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md).

It would be handy from a standpoint of auto-picking which route needs to be taken (similar to extracting salt/workload). Hmmmmm 🤔

**Comment by Indigo744** [comment]
You're right! I didn't know this format... which seems to be the the format for Argon2.
It looked so similar with MCF at first glance I didn't even checked. This is actually good to know!

Well, since this is a bcrypt lib, I don't think there is a point of using PHF... It should remain compatible with crypt.
Anyway, only passlib seems to do this. Even Paragonie's own implementation doesn't do this. I guess it's safe to continue as before.

**Comment by ChrisMcKee** [comment]
Yeah, I won't be breaking the version standard for normal bcrypt. 
Could be useful in the enhanced bit for dealing with hashes created using SHA256 when the libs set to use 512.  
The mass majority will be using the standard crypt route; the likes of dropbox adding a pepper to the user key then hmac512 the b64 then bcrypt. So the base routes are the most important. The enhanced stuffs just basically wrapping some of this up. 
One to ponder, though I'm not wholly keen on altering the hash format, it surfaces the hash type used for decryption; but in the same breath that could be a negative thing.

**Comment by Indigo744** [comment]
Alright. Looking forward the new version. Thanks!
