### ISSUE TITLE
InputKey length

### ISSUE THREAD

**Issue by M22an** [BcryptNet/bcrypt.net#18]
I thought BCrypt only supports hashing upto 72 characters. But I did a few tests yesterday and was able to hash upto 320 characters. 

Ref: https://security.stackexchange.com/a/39851/118192
https://www.usenix.org/legacy/events/usenix99/provos/provos_html/node5.html

Does this library not impose such a restriction ?

**Comment by ChrisMcKee** [comment]
Hi, thanks for the interest. The library maintains expected restrictions, I've added a test to this effect in https://github.com/BcryptNet/bcrypt.net/commit/682b27ffc7129736e3392971f62de6de35fcbdac
