### ISSUE TITLE
Async methods?

### ISSUE THREAD

**Issue by JasonJShuler** [BcryptNet/bcrypt.net#20]
Is there any possibility, or would it make sense to offer async versions of the methods?

Since they are by design time consuming, I thought it might be good to not block. I could wrap it in a Task.Run() but if there are awaitable versions of anything being called within the library it would be better to go all async I would think.

Thanks for making the world a better place!

**Comment by ChrisMcKee** [comment]
There's no asynchronous interface because BCrypt is a CPU bound operation. 
You can make it asynchronous using Task.Run, but I assume you're using it in a web interface so I doubt there would be any gain (vs the overhead). This synchronous nature is in keeping with the .net hashing apis

**Comment by ChrisMcKee** [comment]
In node JS of course they support it in the API
```
Bcrypt supports both sync and async methods. The asynchronous approach is recommended because hashing is CPU intensive, and the synchronous version will block the event loop and prevent your app from handling other requests until it finishes.
```

I'd say if you're in a Win App it would make sense to push off thread to avoid locking up the UI; we've been using it in a web login for ~6 years without any noticeable delay. 

As with all things though; mileage may vary, if in doubt test/benchmark
