### ISSUE TITLE
Problem on BCrypt.Verify()

### ISSUE THREAD

**Issue by Dazorn96** [BcryptNet/bcrypt.net#21]
Here is my code to reproduce:

**Security.cs**
`Security` is a static class
```csharp
private static readonly string strongSalt = "";  // will be assigned a value soon

public static string EncryptString(string input)
{
  try
  {
    string saltedInput = $"{input}{strongSalt}";
    string hash = BCrypt.Net.BCrypt.HashPassword(saltedInput);

    return hash;
  }
  catch(Exception ex)
  {
    Logging.Instance.Error($"(Security/{MethodBase.GetCurrentMethod().Name}): {ex.Message}");
    throw ex;
  }
}

public static bool VerifyHash(string input, string hash)
{
  try
  {
    string saltedInput = $"{input}{strongSalt}";
    return BCrypt.Net.BCrypt.Verify(saltedInput, hash);
  }
  catch(Exception ex)
  {
    Logging.Instance.Error($"(Security/{MethodBase.GetCurrentMethod().Name}): {ex.Message}");
    throw ex;
  }
}
```

**User-Model**
`Hash` is calculated as the same as `ConfirmHash`
```csharp
public class UserRegistration
{
  public ObjectId _id { get; set; }

  public string Email { get; set; }
  public string Hash { get; set; }

  public bool Confirmed { get; set; }
  public string ConfirmHash { get; set; }

  public UserRegistration(string Email, string Hash)
  {
    this.Email = Email;
    this.Hash = Hash;
    this.Confirmed = false;
    this.ConfirmHash = Security.EncryptString(this.Email);
  }
}
```

As you can see, on MongoDB I store the **hash string**...
![db_data](https://user-images.githubusercontent.com/10536581/46462074-b3dc2f00-c7c0-11e8-903b-92a2f8e69674.png)

**Login-logic**
```csharp
bool equal = Security.VerifyHash(password, document.Hash);
return (equal == true ? document.Hash : string.Empty);
```

Same password of registering process... i get `false` everytime.
What's the problem? Thanks :)

**Comment by Dazorn96** [comment]
Resolved.
When i restarted Visual Studio solution it worked.

**Comment by ChrisMcKee** [comment]
@Dazorn96 thanks for the update 👍 VS is an odd beast.

**Comment by ChrisMcKee** [comment]
@Dazorn96 when you store users in mongo it's advisable to use conventions to set the Id field as ID rather than directly referencing the members `objectid` from the mongo bson library (this also allows you to use the more `C#` styled `public Guid Id { get; set; }` ) using guids for ids is also advisable as its helps maintain data portability 👍

**Comment by ChrisMcKee** [comment]
@Dazorn96 
Just for the hell of the codes like this

```
var pack = new ConventionPack();
                pack.Add(new IgnoreExtraElementsConvention(true));
                pack.Add(new NamedIdMemberConvention("Id"));
                ConventionRegistry.Register("my conventions", pack, t => true);
```

You do this before you setup the connection you can also set the GUID representation in Mongo
`BsonDefaults.GuidRepresentation = GuidRepresentation.Standard;`

`IgnoreExtraElementsConvention` Is a handy default as it allows you delete fields from a model at a later date without having to purge the field from mongo.
