### ISSUE TITLE
Hash compatibility with jBCrypt

### ISSUE THREAD

**Issue by lincolnmilner** [BcryptNet/bcrypt.net#22]
I'm having an issue where I have a web app that was originally set to use a version of Damien Miller's jBCrypt.

Hashes with $2a$10$... work fine between jBCrypt and BCrypt.NET (the latest, v3.1.0).  However, hashes with $2a$12$... consistently fail.

Should this be possible?  Is there something I'm missing in setting the Verify() parameters or anything so 12 iteration hashes work like 10 iteration hashes seem to?

**Comment by ChrisMcKee** [comment]
No, the workload is taken from the number in the string; the only changes really between earlier versions were to add the enhanced entropy methods.

I've even used the vectors from jbcrypt in the tests to maintain compatibility (this one being at 12 rounds) 

`https://github.com/svenkubiak/jBCrypt/blob/master/src/test/java/org/mindrot/jbcrypt/TestBCrypt.java#L49-L50` is

**Comment by ChrisMcKee** [comment]
@abbradar 3.1.1 is broken, please use 3.1.2 see #24 for the explanation.
Sorry about that. Seriously.
