### ISSUE TITLE
Enhanced Entropy documentation

### ISSUE THREAD

**Issue by DavidDeSloovere** [BcryptNet/bcrypt.net#23]
First I have to say: thank you for your work on this library. 

Regarding how to use Enchanced Entropy, I didn't understand the description in the readme about it. 
https://github.com/BcryptNet/bcrypt.net#enhanced-entropy

Could you please clarify? Also, is it best to use the Enchanced Entropy or not; or does it depend on something? 
I'm guessing it's not compatible with previous version, I mean that we'll need to make sure we either call Verify or EnhancedVerify based on what hashed password we have stored. And how to know what HashType we pass into EnchancedVerify.

Thanks.

**Comment by ChrisMcKee** [comment]
I'll have a read through in a bit. 
I expect my documentation is crap 😉

**Comment by ChrisMcKee** [comment]
So to use the Enhanced hashing method all you have to do is call it with the enhanced prefix.

```
            const string myPassword = "IPAHJipdfh80adyf80aegh80gfrh";

            var enhancedHashPassword = BCrypt.EnhancedHashPassword(myPassword);

            var validatePassword = BCrypt.EnhancedVerify(myPassword, enhancedHashPassword);
```

If you plan on storing the hmac alongside your auth data for some sort of future proofing (HMACSHA384 is used as its the optimal balance between perf + output / the other options are provided for legacy and allowing compatibility with other implementations in other languages)
you can specify the hmac yourself
```
var enhancedHashPassword = BCrypt.EnhancedHashPassword(myPassword, hashType: HashType.SHA384);

var validatePassword = BCrypt.EnhancedVerify(myPassword, enhancedHashPassword, hashType:HashType.SHA384);
```

**Comment by ChrisMcKee** [comment]
@DavidDeSloovere Updated the docs https://github.com/BcryptNet/bcrypt.net#enhanced-entropy

Let me know if you need any help 👍

**Comment by ChrisMcKee** [comment]
@DavidDeSloovere if you downloaded 3.1.1 please migrate to 3.1.2; The 3.1.1 release was utterly broken 😬

**Comment by ChrisMcKee** [comment]
@daviddesloovere yep that's correct. I could have made it automatic by altering the version but then I'd break compatibility with all the other language implementations. Joys of backwards compatibility

**Comment by DavidDeSloovere** [comment]
All clear now. Thanks again.
