### ISSUE TITLE
[Question] Is this implementation safe from this?

### ISSUE THREAD

**Issue by flacidsnake** [BcryptNet/bcrypt.net#30]
Hi,
do you know if this implementation safe from the attack described here?
https://www.usenix.org/system/files/conference/woot14/woot14-malvoni.pdf

Regards

**Comment by ChrisMcKee** [comment]
Safe from custom fpgas being used to perform a table attack? 

This isn't really something an implementation of a standard hashing method can defend against; but as it stands at 12-13 rounds bcrypt is still one of the safest hashing algorithms around at this time and even if the numbers get up to the 1000/cs range for any non-trivial password (top 4000 list etc) you're still talking about a long time to crack.

Still considerably more expensive than the same attack against PBKDF2 which is the defacto in most systems like .net Identity service (as its NIST approved); but as you'll note from the research the computations per second drop dramatically with the increase in rounds.
