### ISSUE TITLE
Verify password failing with 3.1.3

### ISSUE THREAD

**Issue by sankettandulwadkar** [BcryptNet/bcrypt.net#31]
Hi, 
I am currently working on a new project based on .Net core 2.0 and trying to use the BCrypt.Net-Next package to hash and verify my passwords. I have my old project with all the users; which is a .net framework 4.6.x and uses BCrypt-official. 

I am unable to verify the passwords for those users with the new project. Is it because BCrypt-official uses a different salt/work factor that BCrypt.Net-Next? If I reset the password using BCrypt-official, BCrypt.net-next can verify it and log me in. So I am a little confused as to why the verify from creating it in BCrypt.net-next does not work. 

Sorry, I am very new to BCrypt and security in general and was wondering what the difference b/w BCrypt.net-next and BCrypt.net-next.StrongName.

**Comment by ChrisMcKee** [comment]
We test against the same test vectors as the original solution (https://github.com/BcryptNet/bcrypt.net/blob/master/src/BCrypt.Net.UnitTests/BCryptTests.cs#L33-L53) 
the salt/work is verified based on the full hash passed in. They've all passed https://ci.appveyor.com/project/ChrisMcKee/bcrypt-net/branch/master/tests

The enhanced hashing is opt-in so bcrypt next should be totally backward compatible.

`string hashed = BCrypt.HashPassword(plain, salt, enhancedEntropy: true);`
`var validateHashCheck = BCrypt.EnhancedVerify(plain, hashed);`

You've said that re-hashing your password using `BCrypt-official` and verifying in `BCrypt.net-next` works fine, which validates the above ... but confuses the hell out of me why you have older hashes that fail 😬 

I obviously lack any ability to blindly debug or solve your issue here;

* assuming this is in an auth db were the was the password really long?
* is there any correlation between hash age and being verifiable? 

As for the strong name question; just use the main package; they're both signed now.
The original Nuget/MSFT advice was not to bother; and doing so had forced packages relying on it to also sign. 
They reversed that advice and nuget fixed up their end.

**Comment by sankettandulwadkar** [comment]
Thank you for your prompt reply. 

I was not using EnhancedVerify was using just verify. I shall try it out and update you on the same. 

Yes, I am bit baffled as to why Next is able to verify a password hash created and saved with official, but not itself or the one created by official in the past. One thing I noticed is the work factor for all my old paswords was $2a$10 while the one with next is $2a$11. I changed that but it still is not affecting the output. 

Here is a piece of code that I am using Bcrypt at:

```
password = BCrypt.Net.BCrypt.HashPassword(value, 10); //recently added the 10 to just take out any variables 
bRet = BCrypt.Net.BCrypt.Verify(passwordToCheck, password);

```

**Comment by ChrisMcKee** [comment]
The verify step takes the $WORKLOAD$ from the hash.

"I am bit baffled as to why Next is able to verify a password hash created and saved with official, but not itself or the one created by official in the past."

So you the code you've put above doesn't work for you?

**Comment by ChrisMcKee** [comment]
Just to be extra clear; if you bcrypt was using a default workload of 12
but your DB contained a workload of 6 `$2a$06$DCq7YPn5Rq63x1Lad4cll.` ($06$)
altering that number manually would break the hash.

**Comment by sankettandulwadkar** [comment]
Yes, the above code does not work. I tried with the Enhanced verify function, that didnt do the trick either. 

What I meant by different work factor is, the official one that was used in my old project has passwords and answers saved with $2a$10 while all the ones that Next creates are $2a$11. I dont think it matters, but I wanted to not have anything different. Also, I am never manually modifying any of the hashes. I am only making changes to the functions (like using enhnaced verify instead of verify(which is used in old project) and adding work factor 10 in the new one while the old one doesnt have that field specified.

**Comment by ChrisMcKee** [comment]
Thank god for modern project files (edit build run).
So I setup a quick xunit test and rolled the project to 2.0.1 which is pretty much the first version in the fork and pumped out a bunch of hashes at various workloads based on a static password; then span through them in a loop to test. I've attached that.

![image](https://user-images.githubusercontent.com/83597/55342043-c0a3bc00-549f-11e9-9508-fadb07d91166.png)
![image](https://user-images.githubusercontent.com/83597/55342117-f21c8780-549f-11e9-9b58-8ba47f11de0f.png)

[XUnitTestProject3.zip](https://github.com/BcryptNet/bcrypt.net/files/3030375/XUnitTestProject3.zip)

**Comment by sankettandulwadkar** [comment]
Hi Chris,

I wanted to update you on the issue I was having. I ended up moving my projects into a different environment and it is now working both ways i.e., Official->.Net-next and vice versa. However, it is still not working on the previous environment. 

The previous environment was two windows 2012 r2 servers with 4G ram and 64 bit OS. One has the old code with official and the other has new code with .Net-next. I am not able to verify passwords on this setup.

My new one is windows 7  with 16G ram and it works fine with it. 

As far as I am aware, the systems should not matter. Are there any IIS settings that need to be made to have it work on 2012 r2? Or any other adjustments needed? Any help on this would be appreciated.

Thank you!

**Comment by ChrisMcKee** [comment]
@sankettandulwadkar I'm guessing its a web project? is the text making it to the call unaltered? 
Just wondering if there's a difference between encoding causing the hash or the password to be altered before verification; something that in an old solution may have been configured via culture or web/app config or global.asax overload?

We run this in production on Alpine/Ubuntu (docker)/Ubuntu 16/18lts (metal)/ and server 2012r2 and 2016 and have test hashes going back to 2014 so it's pretty battle tested

**Comment by ChrisMcKee** [comment]
@sankettandulwadkar did you by any chance work out the difference between the machines?

**Comment by sankettandulwadkar** [comment]
@ChrisMcKee No, no leads yet. I am almost certain its a environment issue over BCrypt issue. However, I would like to get it working before I close this one. I shall update you once I have more context about the same.

**Comment by ChrisMcKee** [comment]
@sankettandulwadkar the bot will probably kill the ticket if its left untouched but feel free to update it anyway; I like an ending 👍
