### ISSUE TITLE
Verify password not working

### ISSUE THREAD

**Issue by geniusKoder** [BcryptNet/bcrypt.net#32]
I have tried it before in previous versions, but it didn't work out. I'm trying it again and it doesn't work out. The error is seen below.

```
SaltParseException: Invalid salt version
BCrypt.Net.BCrypt.HashPassword(string inputKey, string salt, bool enhancedEntropy, HashType hashType) in BCrypt.cs, line 633
```

In the documentation, it says to use this but it doesn't work out. `BCrypt.Verify("my password", passwordHash);`

As a workaround, I had to separately store the hash and then compare it instead. Hope to be able to fix the Bcrypt.Verify bug as it makes the code much cleaner.

```
var userSuppliedPasswordhash = BCryptPasswordHash.HashPassword(<user password>, <salt>);

if (storedPassword.Equals(userSuppliedPasswordhash)){
...
}
```

**Comment by ChrisMcKee** [comment]
Hi; without an example I can't do much. If you look at the tests you'll see there's a pretty large amount of coverage of this stuff. 

Can you give me an example hash that throws that example and the password?

**Comment by geniusKoder** [comment]
I generate the salt first `BCrypt.GenerateSalt(13);`, then I hash the password `BCrypt.HashPassword(password, salt);` then I verify` BCrypt.Verify(password, storedHash);`

The password I tested with was Pass123!

**Comment by geniusKoder** [comment]
Example this is the password $2a$13$a4HERsk1x9QWmcWRInVW4em0UK9FhRMLzletX0uYdCDCNOnEgpFQG
and I have to store the salt separately ($2a$13$a4HERsk1x9QWmcWRInVW4e) since the verify method wouldn't work.

So I generated the salt and hashed it with the plaintext, and I wanted to use the .Verify method but it doesn't work, so I took the extra salt that I stored, hashed it with the plaintext and compared the current plaintext against the one that I have stored, which is all good, but it's weird why I can't use the default API to do it instead.

Error:
```
An unhandled exception occurred while processing the request.
SaltParseException: Invalid salt version
BCrypt.Net.BCrypt.HashPassword(string inputKey, string salt, bool enhancedEntropy, HashType hashType) in BCrypt.cs, line 633
```

```
public static bool ValidatePassword(string password, string storedHash)
        {
            return BCrypt.Net.BCrypt.Verify(password, storedHash);
        }
```

**Comment by ChrisMcKee** [comment]
The only way that exception is raised is if the first char isn't $ and the second isn't 2 as that's the mark of bcrypt

**Comment by ChrisMcKee** [comment]
@geniusKoder Passing the hash `$2a$13$a4HERsk1x9QWmcWRInVW4em0UK9FhRMLzletX0uYdCDCNOnEgpFQG` in to a test 
![image](https://user-images.githubusercontent.com/83597/55785360-32849280-5aaa-11e9-849c-64f91121d126.png)
and running it, it worked (failed as I dont know the password and I'm not guessing) fine, passing the salt validation checks.

I can only assume you have something weird in your code base like appending a non-visible whitespace character or an encoding issue in the string.

If you can throw together a small **failing** console job; zip it and attach to the issue I'll take a further look.

**Comment by mrabubaker101** [comment]
f

**Comment by ashnoori11** [comment]
i have problem with this . the verify method does not work
