### ISSUE TITLE
Verify() :: Unknown Salt - Porting to NetCore Version

### ISSUE THREAD

**Issue by iby-dev** [BcryptNet/bcrypt.net#33]
HI, I think I have a similar situation to other issues on here.

I have been using [this ](https://www.nuget.org/packages/BCrypt-Official/)for a while now but with with an older api that i inherited and i don't know the salt value. We are porting it to netcore and noticed the same call to verify works in the older lib but with this new one. Any ideas?

The hashed passwords all come from a financial db that we call into to so i have no idea how they are hashed. 

All we did before was provide a password and a matching hash was found linked to the email address and then this was pushed into `Verify()`.

So i am not so sure now what to do?

**Comment by iby-dev** [comment]
Sorry - copy and pasta'd!!!

Working now.

**Comment by ChrisMcKee** [comment]
Cool; as I've said in the previous ones the hashes and salts shouldn't really be split; and salt generation should be left to the hash call rather than generated separately. Down the line I'll probably depreciate and remove the direct call to salt.

**Comment by ChrisMcKee** [comment]
Thanks for the update; copy & paste gets us all in the end 😉
