### ISSUE TITLE
'That assembly does not allow partially trusted callers' Error on shared hosting platforms.

### ISSUE THREAD

**Issue by StarrrLiteNL** [BcryptNet/bcrypt.net#38]
I am trying to use this library in a project I am working on. Locally it is working fine, however as soon as I deploy it to my (shared) webhost, I get the error "That assembly does not allow partially trusted callers". I have no access to IIS on the server, because it's a shared hosting platform.

From what I have read this can be fixed by addding  [assembly:AllowPartiallyTrustedCallers] to the assemblyinfo.cs file. I would assume more people would have run into this, so there might be an easier solution?

**Comment by ChrisMcKee** [comment]
What version of .net and IIS/Win are you on?

**Comment by StarrrLiteNL** [comment]
I stand corrected, turns out the partial trust error wasn't caused by bcrypt.net, but by another reference that i called right under it.
