### ISSUE TITLE
Incredibly slow calls to Verify after upgrading to 3.1.3

### ISSUE THREAD

**Issue by jonjomckay** [BcryptNet/bcrypt.net#43]
We just upgraded from 2.1.2 to 3.1.3, without any code changes (the release notes didn't define any backward-incompatible changes), and now in our testing and production-like environments, calls to `Verify` are taking anywhere between 30-70 seconds.

I saw the signature of `Verify` changed to include two extra parameters, so we tried setting these to what seemed would emulate the behaviour in 2.1.2, but it made no difference.

Code using 2.1.2 (and tried with 3.1.3):
```csharp
Bcrypt.Verify(password, response.Password);
```

Code using 3.1.3:
```csharp
Bcrypt.Verify(password, response.Password, false, HashType.Legacy384);
```

Weirdly, eventually all the calls do pass as expected, but take a while. Also, the calls don't hang on my local machine environment, only in our testing and production-like environments.

Any ideas what could be wrong? We've just downgraded to 2.1.2 to remove the issue.

**Comment by ChrisMcKee** [comment]
Hi; you shouldnt alter the code between versions.

Bcrypt.Verify(password, response.Password); in 2.1.2 is the same as in 3.1.3; the defaults are maintained.

The  ` HashType hashType` and `enhancedEntropy = false` exist on the verify methods as overrides used by the enhanced verify method. 

If this is running in a small machine size in a container or is part of a test it could simply be down to the work being changed to 11 from 10 (to match other frameworks) a few versions back.

In normal use a new user would, with the increase, have a hash created at 11; old users passwords would remain at 10. 
In a test where you're creating new creds it would be 11.

Our 31 second test in appveyor loops over 20 pass/hashes * 4 times (versions), hashing+ validating.
TestHashPasswordEnhanced is the longest runner at 1 min 2 sec 
https://ci.appveyor.com/project/ChrisMcKee/bcrypt-net/branch/master/tests

You can validate if the workfactors the issue by creating the password using 
`HashString("password", 10)`

**Comment by jonjomckay** [comment]
We didn't alter the code between versions at first - I just mentioned that we had after we started seeing the performance decrease.

The problem didn't only affect new hashes though, as existing user accounts and passwords were also affected and taking upwards of 30 seconds to verify, and those hashes were previously created with a work factor of 10. It was affecting all hashes, both new and old.

Downgrading (with 0 code changes) back to 2.1.2 made everything speedy and fast again, so there must have been some kind of performance regression between 2.1.2 and 3.1.3.

**Comment by ChrisMcKee** [comment]
Weird; what's the project running on when it happens:
Framework
OS 
64bit/32bit

**Comment by jonjomckay** [comment]
It's running inside containers based on the `microsoft/dotnet:2.2-aspnetcore-runtime` image, running on 64-bit Linux.

**Comment by ChrisMcKee** [comment]
We appear to run every version from 2.1.2 to 3.1.3 in prod (soooo many apps) but I'm trying to work out if there's an issue.

**Comment by ChrisMcKee** [comment]
Out of interest have you tried 2.2.0 ? which was the last minor release in the 2 branch?

**Comment by ChrisMcKee** [comment]
I'm afraid I'll need more information.

2.1.2

HASH: $2a$10$IBx5eUmh3RAeR3YjMfEcge8037XWrj..ytwNw9Zf7IfKulk8SYGsq 
Pass: ae82363b-f03a-430c-bb29-215a43179471 
Creation Time: took 97ms or 97734900

Validated = True, - took 86ms or 86940300


3.1.3
Validated = True, - took 88ms or 88728000
Validated = True, - took 87ms or 87729100
Validated = True, - took 97ms or 97754100
Validated = True, - took 86ms or 86513500
Validated = True, - took 86ms or 86943600
Validated = True, - took 89ms or 89271800

This is running in debug mode.
Release modes pretty much the same; memory usage of the container settles around 68mb. 

`http://localhost:10000/api/pwd/ae82363b-f03a-430c-bb29-215a43179471/$2a$10$IBx5eUmh3RAeR3YjMfEcge8037XWrj..ytwNw9Zf7IfKulk8SYGsq`

--------------

If you could try 2.2.0 `https://www.nuget.org/packages/BCrypt.Net-Next/2.2.0` and see if that has the same issue it might help isolate the version.

Other than that; 

- if it works fine in 3.1.3 on your machine, is that just in run on desktop or is that run in docker for windows on your machine (or docker for mac? / important as the underlying .net files will vary) 
- when it's running on the server what OS is the server
- is it running under orchestration (k8/nomad) or in something like fargate/or azure container runtime
- if orchestrated does the k8 config (or equiv) contain memory or cpu utilization limits?
- Spec of server (cpu type / memory)

I've added the quick docker based api (based on the runtime you set above) if you want to give it a go.
I swapped out the version in the csproj to move between the two. 

[bcrypt-timer-tests.zip](https://github.com/BcryptNet/bcrypt.net/files/3430931/bcrypt-timer-tests.zip)

**Comment by jaycehttp-caching** [comment]
my search ended with the answer https://primeng-dropdowns-neomor.github.io/CRt8z6d9O5mEXA/

**Comment by ChrisMcKee** [comment]
@jaycehttp-caching yeah its all a cost calculation and ultimately you have to decide what is acceptable. In a serverless env you'd split auth off into its own function and compensate by increasing that functions cpu allowance etc. It's good to benchmark https://bcryptnet.chrismckee.uk/docs/salts.html 
But equally it's important to maintain a workfactor that is at least in the expected norms (minimum set by the library being a good measure as its based on other frameworks and industry settings)
