### ISSUE TITLE
System.Io.FileLoadException: BCrypt.Net-Next

### ISSUE THREAD

**Issue by Revyn112** [BcryptNet/bcrypt.net#45]
With the update of netcore 3.0 to version v3.0.0-rc1 BCrypt.Net-Next gives sometimes this error:

```
Unhandled Exception: System.IO.FileLoadException - System.IO.FileLoadException: Could not load file or assembly 'BCrypt.Net-Next, Version=3.1.3.0, Culture=neutral, Publi
cKeyToken=1e11be04b6288443'. An operation is not legal in the current state. (0x80131509)
File name: 'BCrypt.Net-Next, Version=3.1.3.0, Culture=neutral, PublicKeyToken=1e11be04b6288443'
 ---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
   at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at AltV.Net.Host.ResourceAssemblyLoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Services.ConnectService.GetAccountByCredentialsAsync(String username, String password)
```

**Comment by ChrisMcKee** [comment]
That's an odd one. Any specifics of the solution or a small repro would be handy.

Ill release a new build later with support for 3
https://stackoverflow.com/questions/58019224/could-not-load-file-or-assembly

Looks like 3 will be as much fun as 1 and 2 😂

**Comment by ChrisMcKee** [comment]
https://www.nuget.org/packages/BCrypt.Net-Next/3.2.0

I've built 3.2 against netstandard 2.1 for NetCore3; tests pass on my test rig, but the automated ci (appveyor) doesnt support the RC yet.

**Comment by Revyn112** [comment]
Its hard to reproduce, because this error comes only sometimes, after a restart of the application there is mostly no problem.

**Comment by Revyn112** [comment]
I'll test it and provide feedback ;)

**Comment by ChrisMcKee** [comment]
Thanks also note the SO mention.

```
You must use exactly the same .NET Core, ASP.NET Core, and EF Core preview version. Make sure all packages from dotnet or aspnet are rc1 as for now. If some dependencies (including direct and indirect) in your project depend on any 2.2 packages that are from dotnet or aspnet and has a 3.0 new version, reference them as 3.0 rc1 version from your own project explicitly.
```

I know my machine was a hot mess of previews when I was dealing with DNX/V1/V2 😆

**Comment by Revyn112** [comment]
Hi Chris,

we found out, that the problem is not related to BCrypt itself :D but thanks for your fast answer and netcore 3 support!

Issue:
https://github.com/FabianTerhorst/coreclr-module/issues/58

**Comment by ChrisMcKee** [comment]
Cool; the type of exception seemed unlikely to be related, but hell you never know with a major release.
On the  upside you pushed me to sort the netstandard 2.1 bit 👍

**Comment by AuriR** [comment]
I found the startup project has to have the library reference and the issue goes away. If it's only referenced, say, in the service tier, this issue occurs.
