### ISSUE TITLE
First run from BCrypt.HashPassword() takes more time

### ISSUE THREAD

**Issue by Indigo744** [BcryptNet/bcrypt.net#46]
Hello,

I have recently created a quick project to be able to find the best cost for our server. The code is really simple and available in this Gist: https://gist.github.com/Indigo744/b6cce04b8a1bfcef90a43ea1302c4701

I noticed that the first call to `BCrypt.HashPassword()` will always yield a longer time than expected:
```
Testing cost value of 4: ... took 29ms
Testing cost value of 5: ... took 4ms
Testing cost value of 6: ... took 8ms
Testing cost value of 7: ... took 16ms
```

If I add before the `do...while()` loop a simple "warmup" call like `BCrypt.HashPassword("t", 4);`, then I get correct results:
```
Testing cost value of 4: ... took 2ms
Testing cost value of 5: ... took 4ms
Testing cost value of 6: ... took 8ms
Testing cost value of 7: ... took 16ms
```

What do you think?

I suspect a lazy initialization from .Net somewhere but I'm not sure. 
Maybe it corresponds to the time it takes to load the huge `SOrig` static array in memory?
I would appreciate your thoughts on this.

Thank you!

**Comment by ChrisMcKee** [comment]
Hi, thanks for the gist.
It's an interesting question and one I can't admit I've looked at with regards to this library; but in general all warm up scripts skip the first hit in .net as there's a lot of ".net stuff" going on at that point.

For benchmarking code you're better using something like benchmark.net https://benchmarkdotnet.org/  (nice tut/intro here https://dotnetcoretutorials.com/2017/12/04/benchmarking-net-core-code-benchmarkdotnet/ )  

When you set the cost its good to remember 1 secnod is a life time in code and if you're running in a container chances are your resources will be more restricted than code running on a single instance. 
Most bcrypt workloads are in the 9-11 area as it's a good level of protection vs performance.

I'd also look at the enhanced method as it does 'very little extra' but it ensures any use of "memorable passwords" or passphrases that exceed the character limit of bcrypt aren't truncated / the entropy is retained. 

I doubt its related to the loading of SOrig directly as its essentially a static global; but where the cause may lie is in InitializeKey where the SOrig and POrig array are copied into the local var _p/_s as what may be happening after the first run is JIT optimizing for further copies. 

Interesting one though :)

**Comment by Indigo744** [comment]
Thanks for the reply.

It's a simple benchmark code to quickly check if a particular system build will yield good result. It's by no mean to be exactly accurate to the µs. It just help to answer the question _"can we use this cost? Is it acceptable on this client?"_.

But thanks for the benchmarking links. Could come in handy if I ever need precise measurement 😸
