### ISSUE TITLE
Incorrect timestamps in newest NuGet package's DLL files

### ISSUE THREAD

**Issue by NikoHellgren** [BcryptNet/bcrypt.net#47]
DLL files in the 3.2.0 NuGet package (see commit https://github.com/BcryptNet/bcrypt.net/commit/b12c467a09101e0f177859e5a1e6741b67fe0bc4) have an incorrect Modified-timestamp (1980-01-01 00:00). This has the possibility of breaking build processes (see https://github.com/NuGet/Home/issues/7001).

**Comment by ChrisMcKee** [comment]
Ta! bloody tooling

**Comment by ChrisMcKee** [comment]
https://github.com/dotnet/core/issues/3388

**Comment by ChrisMcKee** [comment]
Added 
```
<PropertyGroup>
    <Deterministic>false</Deterministic>
</PropertyGroup>
```
For now; I'll push a .1 rel to deal with it
![image](https://user-images.githubusercontent.com/83597/65837811-a1250900-e2f3-11e9-818e-7a3e3407955a.png)
