### ISSUE TITLE
Weird path showing up in logs

### ISSUE THREAD

**Issue by antja0** [BcryptNet/bcrypt.net#52]
# Info

**BCrypt.NET-Next version 3.2.1**

> System.ArgumentException: Invalid salt
> Parameter name: salt
>    at BCrypt.Net.BCrypt.HashPassword(String inputKey, String salt, Boolean enhancedEntropy, HashType hashType) in C:\Users\chris\source\repos\bcrypt.net\src\BCrypt.Net\BCrypt.cs:line 614
>    at BCrypt.Net.BCrypt.Verify(String text, String hash, Boolean enhancedEntropy, HashType hashType) in C:\Users\chris\source\repos\bcrypt.net\src\BCrypt.Net\BCrypt.cs:line 838

I got this error log in server logs **when parsing a empty password** from a database.
So basically parsing an empty string with ```BCrypt.Net.BCrypt.Verify()```

# Issue

I'm confused why the path "C:\Users\chris..." is printed in our logs.
There is no user named chris in the server. This path simply does not exist.
However, it seems like there is a contributor named chris in this repo.

Are you aware of this? Care to explain?

**Comment by antja0** [comment]
Also consider throwing more descriptive error message if string being parsed is empty.

**Comment by ChrisMcKee** [comment]
The builds require signing so they're built on my machine; dotnet stores the src path for stack traces. 
You can of course exclude the pdb file which provides the level of detail but as this is a library and raising exceptions to an application it's usually preferred that its traceable.
