### ISSUE TITLE
Framework targeting incorrect

### ISSUE THREAD

**Issue by jvandertil** [BcryptNet/bcrypt.net#61]
Hello,

There seems to be an issue with the framework targeting for the NuGet package.
If you look at the package on [NuGet](https://www.nuget.org/packages/BCrypt.Net-Next/) then it appears that there are no dependencies listed. This is strange, I expected to see System.Memory somewhere.

Also, the performance improvements (that use Span) do not seem to be part of the NuGet package.
The `netstandard2.1` assembly in the package still has the 'old' signatures that use arrays, as seen below in the ILdasm screenshot.

![image](https://user-images.githubusercontent.com/158879/76294657-8e0b6180-62b3-11ea-8a58-4ffbdcb9a1f6.png)

I believe the error is in the way the `HAS_SPAN` compile time constant is defined.

Currently it is:
```xml
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0|net452|net462|net472'">
    <PackageReference Include="System.Memory" Version="4.5.3" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1|netstandard2.1|netstandard2.0|net452|net462|net472'">
    <DefineConstants>$(DefineConstants);HAS_SPAN</DefineConstants>
  </PropertyGroup>
```

As far as I know the MSBuild '==' operator performs an exact string match.

I believe that this is the correct way to define the dependency and constant:
```xml
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'
                         or '$(TargetFramework)' == 'net452'
                         or '$(TargetFramework)' == 'net462'
                         or '$(TargetFramework)' == 'net472'">
    <PackageReference Include="System.Memory" Version="4.5.3" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1'
                         or '$(TargetFramework)' == 'netstandard2.1'
                         or '$(TargetFramework)' == 'netstandard2.0'
                         or '$(TargetFramework)' == 'net452'
                         or '$(TargetFramework)' == 'net462'
                         or '$(TargetFramework)' == 'net472'">
    <DefineConstants>$(DefineConstants);HAS_SPAN</DefineConstants>
  </PropertyGroup>
```

**Comment by ChrisMcKee** [comment]
I think the dependency graph issue in nuget is caused by the lack of a nuspec specifying the dependency. I've not really gone back to check if they changed the csproj format to allow extra fields for this or not. 

Can't remember where the hell I found the target framework shortcut from but it _did_ work when it was added 😞 . VS is now showing it grey so it seems dead. 

I'm removing net47 from the targets as that should be safely covered by netstd2; I'm also reducing span coverage to netstd up.

**Comment by ChrisMcKee** [comment]
https://stackoverflow.com/a/48826063/52912 changed last year in feb to require nuspec fml

**Comment by jvandertil** [comment]
Yeah, but there are only `PackageReference` entries. So you shouldn't need an additional nuspec to fix that. MSBuild does not understand the `Condition` property to be a set of 'or' conditions and thus does not output it. Same with the constants

**Comment by ChrisMcKee** [comment]
![image](https://user-images.githubusercontent.com/83597/76306943-bac57600-62bf-11ea-8987-a7cfc6e9b595.png)
Yep seems fine fixed up locally

**Comment by ChrisMcKee** [comment]
![image](https://user-images.githubusercontent.com/83597/76307419-b3529c80-62c0-11ea-9f2e-be0d6973c0c7.png)
so long as .net 2 stays happy we're all good for  keeping enterprises up to date 😆 

Thanks for that, again, I'd planned on manually testing the versions later on so good spot.

**Comment by ChrisMcKee** [comment]
.net 4.8 console app seems to go for the bloody 4.x ref rather than netstandard2 😱

**Comment by ChrisMcKee** [comment]
Sorted. god that targeting formats ugly.

**Comment by ChrisMcKee** [comment]
![image](https://user-images.githubusercontent.com/83597/76308718-51476680-62c3-11ea-8d03-f4cd5d796a88.png)
from .net 4.8 project

**Comment by jvandertil** [comment]
Awesome, thanks for the quick fix 😄
