### ISSUE TITLE
SHA instances aren't disposed

### ISSUE THREAD

**Issue by MiltoA** [BcryptNet/bcrypt.net#64]
AFAIU, an instance of `SHA256`, `SHA384` or `SHA512` should be disposed after use since it implements `IDisposable`. E.g., [in the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha256?view=netstandard-2.0#examples) they wrap the SHA-related code with `using` statement. I guess the same should be done [here](https://github.com/BcryptNet/bcrypt.net/blob/master/src/BCrypt.Net/BCrypt.cs):
```csharp
private static byte[] EnhancedHash(byte[] inputBytes, HashType hashType)
{
    switch (hashType)
    {
        case HashType.SHA256:
            inputBytes = SafeUTF8.GetBytes(Convert.ToBase64String(SHA256.Create().ComputeHash(inputBytes)));
            break;
        case HashType.SHA384:
            inputBytes = SafeUTF8.GetBytes(Convert.ToBase64String(SHA384.Create().ComputeHash(inputBytes)));
            break;
        case HashType.SHA512:
            inputBytes = SafeUTF8.GetBytes(Convert.ToBase64String(SHA512.Create().ComputeHash(inputBytes)));
            break;
        case HashType.Legacy384:
            inputBytes = SHA384.Create().ComputeHash(inputBytes);
            break;
        default:
            throw new ArgumentOutOfRangeException(nameof(hashType), hashType, null);
    }

    return inputBytes;
}
```

**Comment by ChrisMcKee** [comment]
IDisposable in .net is a skip fire of legacy (hence the old HTTPClient is disposable, lets make a new one for every call... what do you mean that wasn't how its supposed to be used; endless battle)

The calls in SHAXXX (lets say 512 here) to dispose just call the base hashingalgorithm method as its part of the framework expectations https://github.com/dotnet/runtime/blob/master/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/SHA512.cs#L56-L57
Which ultimately just calls dispose on base which has a nice note.
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/HashAlgorithm.cs#L186-L188
```
                // Although we don't have any resources to dispose at this level,
                // we need to continue to throw ObjectDisposedExceptions from CalculateHash
                // for compatibility with the .NET Framework.
```

So the value of making the dispose wrapper / calls appears limited/worthless

**Comment by MiltoA** [comment]
> The calls in SHAXXX (lets say 512 here) to dispose just call the base hashingalgorithm method as its part of the framework expectations

Well, first of, I wouldn't be so sure about that. From the way the value of [`_hashProvider` is set](https://github.com/dotnet/runtime/blob/90e090553fdf7db26cd7998226bf9f82bdceda52/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/SHA512.cs#L32), the [`_hashProvider.Dispose()`](https://github.com/dotnet/runtime/blob/90e090553fdf7db26cd7998226bf9f82bdceda52/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/SHA512.cs#L56) seems to be doing *some* job, and that job is OS-specific ([Windows](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Security.Cryptography.Algorithms/src/Internal/Cryptography/HashProviderDispenser.Windows.cs), [Unix](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Security.Cryptography.Algorithms/src/Internal/Cryptography/HashProviderDispenser.Unix.cs), [OSX](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Security.Cryptography.Algorithms/src/Internal/Cryptography/HashProviderDispenser.OSX.cs)).

And second, even if we agree that there's no harm in not disposing a SHA-2 instance currently, there's no guarantee that it's going to be like that in the future. So, I guess it's better to wrap all SHA instances in `using` statements just to be on the safe side. Since it doesn't cost anything and makes the code more robust, I see no reason not doing it.

**Comment by ChrisMcKee** [comment]
HashProviderDispenser just creates a hash provider via the systems native provider. I had totally forgotten how god awful it is to have the core clr open on my machine. 
And yeah the SafeEvpMdCtxHandle contexts are disposed of in the Windows/Unix ones, so there's that. Bit nightmare fuel tracing if the release is called in the dispose so 🤷‍♂️  may as well go with it

**Comment by MiltoA** [comment]
@ChrisMcKee, :thumbsup:

**Comment by ChrisMcKee** [comment]
Tis in master
