### ISSUE TITLE
Prehashing causes interoperability issues

### ISSUE THREAD

**Issue by MiltoA** [BcryptNet/bcrypt.net#65]
This is the fragment of [the source code](https://github.com/BcryptNet/bcrypt.net/blob/master/src/BCrypt.Net/BCrypt.cs) responsible for prehashing:
```csharp
private const string Nul = "\0";

...

public static string HashPassword(string inputKey, string salt, bool enhancedEntropy, HashType hashType = DefaultEnhancedHashType)
{
    ...
    byte[] inputBytes = SafeUTF8.GetBytes(inputKey + (bcryptMinorRevision >= 'a' ? Nul : EmptyString));

    if (enhancedEntropy)
    {
        inputBytes = EnhancedHash(inputBytes, hashType);
    }

    ...

    byte[] hashed = bCrypt.CryptRaw(inputBytes, saltBytes, workFactor);

    // Generate result string
    var result = new StringBuilder(60);
    result.Append("$2").Append(bcryptMinorRevision).Append('$').Append(workFactor.ToString("D2")).Append('$');
    result.Append(EncodeBase64(saltBytes, saltBytes.Length));
    result.Append(EncodeBase64(hashed, (BfCryptCiphertext.Length * 4) - 1));

    return result.ToString();
}

...

private static byte[] EnhancedHash(byte[] inputBytes, HashType hashType)
{
    switch (hashType)
    {
        case HashType.SHA256:
            inputBytes = SafeUTF8.GetBytes(Convert.ToBase64String(SHA256.Create().ComputeHash(inputBytes)));
            break;
        case HashType.SHA384:
            inputBytes = SafeUTF8.GetBytes(Convert.ToBase64String(SHA384.Create().ComputeHash(inputBytes)));
            break;
        case HashType.SHA512:
            inputBytes = SafeUTF8.GetBytes(Convert.ToBase64String(SHA512.Create().ComputeHash(inputBytes)));
            break;
        case HashType.Legacy384:
            inputBytes = SHA384.Create().ComputeHash(inputBytes);
            break;
        default:
            throw new ArgumentOutOfRangeException(nameof(hashType), hashType, null);
    }

    return inputBytes;
}
```

Judging from it and simply put, the raw bytes that are passed into bcrypt hash-function are derived as:
* if prehashing isn't used
```csharp
byte[] bcryptInput = Encoding.UTF8.GetBytes(password + "\0");
```
* with prehashing
```csharp
byte[] passwordBytes = Encoding.UTF8.GetBytes(password + "\0");
byte[] bcryptInput = Encoding.UTF8.GetBytes(Convert.ToBase64String(SHA256.Create().ComputeHash(passwordBytes)));
```
This raises questions:
1. **When prehashing is used, why is null-terminating char added to the password?**
It looks like there's no reason to do that, because the password is then passed through SHA-2, which will process it anyway (with or without null-terminator), so adding it seems like unnecessary work. Maybe you could clarify.
2. **When prehashing is used, why isn't null-terminator added to the end of base64-string?**
Basically base64-string acts here like a password, which normally gets appended a null-terminator before being converted from string representation into bytes for bcrypt (as shown in the pseudo-code fragment without prehashing). Hope you can clarify this.

The second issue causes serious interoperability problem. When coding for different platform where there's no BCrypt.Net-Next library, the prehashing code can't be easily reproduced: one can generate base64-string the same exact way, but when it gets passed through bcrypt, it will automatically be appended with null-character (which doesn't happen in BCrypt.Net-Next when prehashing is used)
```csharp
string password = "MyPassword";
string prehashedPassword;
using (var sha256 = SHA256.Create())
    prehashedPassword = Convert.ToBase64String(sha256.ComputeHash(Encoding.UTF8.GetBytes(password + "\0")));
// Null-terminator gets appended inside this method, before converting argument into bytes:
string hash = SomeOtherBcryptLibrary.HashPassword(prehashedPassword);
```
The same is true for verification:
```csharp
string hash = "$2b$12$...";
string password = "MyPassword";
string prehashedPassword;
using (var sha256 = SHA256.Create())
    prehashedPassword = Convert.ToBase64String(sha256.ComputeHash(Encoding.UTF8.GetBytes(password + "\0")));
// The method computes bcrypt-hash for the supplied password and compares it to the supplied hash;
// it adds null-terminating character to the password before running it through bcrypt - something BCrypt.Net-Next doesn't do when prehashing is used:
bool isPasswordValid = SomeOtherBcryptLibrary.Verify(hash, prehashedPassword);
```
As a result, if prehashing is used in BCrypt.Net-Next
* hashes generated in BCrypt.Net-Next can't be verified in a 3rd-party bcrypt library;
* hashes generated in a 3rd-party bcrypt library can't be verified in BCrypt.Net-Next (using built-in prehashing mechanism).

The workaround is to use 3rd-bcrypt library that accepts password as bytes, not string - this will allow to reproduce the hashing steps of BCrypt.Net-Next exactly. But most libraries don't support hashing raw bytes (including BCrypt.Net-Next itself).

And back to the first issue, not adding null-terminator to the password while prehashing simplifies the code. With both issues fixed the code would look like
```csharp
string password = "MyPassword";
string prehashedPassword;
using (var sha256 = SHA256.Create())
    prehashedPassword = Convert.ToBase64String(sha256.ComputeHash(Encoding.UTF8.GetBytes(password)));
string hash = AnyBcryptLibrary.HashPassword(prehashedPassword)
```
This code still solves the problem of long passwords for bcrypt and uses SHA-2 prehashing. But it requires an implementation of bcrypt that accepts password as a string - a functionality commonly supported in other bcrypt libraries, which makes this code highly interoperable. So, I suggest using this approach for prehashing in BCrypt.Net-Next.

**Comment by ChrisMcKee** [comment]
Death by lack of test vectors over the extended hash for other frameworks. 
The null terminator is part of the bcrypt 2a specification. 

```
 $2a$

The original specification did not define how to handle non-ASCII character, nor how to handle a null terminator. The specification was revised to specify that when hashing strings:

    the string must be UTF-8 encoded
    the null terminator must be included
```
The jbcrypt (which this was a port of originally) https://github.com/jeremyh/jBCrypt/blob/master/src/main/java/org/mindrot/BCrypt.java#L677 includes the null in the same manner. I've just "muddied" the code in adding the prehashing. 

Ideal world I'd have ignored all this and people would just pass in a SHA'd password. I've added a fix, but this would be a breaking change so I need to try and grab some non .net sha'd hashes for the tests.

**Comment by ChrisMcKee** [comment]
So in fixing

* v.3.5 will contain the ability to both validate and hash using the fixed v4 method; but also contains the default route of using the existing code for those who don't care / are fine with that.
* v4  removes the v3 mistake and defaults to using just the passlib compatible method.

hashes were generated using

```python
import base64
import hashlib
from passlib.hash import bcrypt

keys = ["", "a", "abcdefghijklmnopqrstuvwxyz", "~!@#$%^&*()      ~!@#$%^&*()PNBFRD"]

for key in keys:
    password = key
    hashstring = hashlib.sha256(password.encode('utf-8')).digest()
    encodedBytes = base64.b64encode(hashstring)
    encodedStr = str(encodedBytes, "utf-8")
    print(bcrypt.using(rounds=7).hash(encodedStr))

```

I'll undoubtedly have to dig out a php version.

**Comment by ChrisMcKee** [comment]
@MiltoA thanks for the heads-up.
About 99% of the usage of this lib is for the non-hashed functionality afaik as its compatible with the original library and jbcrypt. But it's good to to have other eyes over it  (and yes I should have added those test vectors way back). 
Thanks again 😁

**Comment by snekbaev** [comment]
@ChrisMcKee Hi, I pulled the v4 into linqpad, took my existing 3.x hash and checked with `BCrypt.Net.BCrypt.Verify(string, string)` and it passed. Given I use this method and `BCrypt.Net.BCrypt.HashPassword(string)` I should be good to upgrade safely as the breaking change is related to the functionality not being used in my case, right? Just confirming before updating and testing :)
Thank you!

**Comment by ChrisMcKee** [comment]
@snekbaev yeah it only effects the SHA hashed route. The standard routes are unaffected (we already had good pre-existing vectors to test the classic route as well so it should stay safe anyway).

**Comment by MiltoA** [comment]
> @MiltoA thanks for the heads-up.

@ChrisMcKee,  you're welcome)
