### ISSUE TITLE
Does bcrypt.net run correctly in 32-bit x86 Linux?

### ISSUE THREAD

**Issue by SaSiNO97** [BcryptNet/bcrypt.net#71]
Does bcrypt.net run correctly in 32-bit x86 Linux?

**Comment by ChrisMcKee** [comment]
It will run wherever .net core runs (on a linux front); and its limitations are solely related to that.

Currently .net core doesn't explicitly support 32bit Linux (https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-linux) and considering most distros killed off support 3 years ago (https://www.pcworld.com/article/3089509/end-of-an-era-linux-distributions-will-soon-stop-supporting-32-bit-pcs.html) I'm not sure if they'll make the requisite efforts to add support. 

* https://github.com/dotnet/runtime/issues/7335
* https://github.com/dotnet/source-build/issues/1235
