### ISSUE TITLE
GetWorkFactor method is not visible because HashParser is internal

### ISSUE THREAD

**Issue by ikrmkg** [BcryptNet/bcrypt.net#81]
Hi,

In my current project I'm migrating passwords work factor from 10 to 5. And I would like to use HashParser.GetWorkFactor method to check work factor of hashed password. But I can not since HashParser is an internal class. Ofc I can use reflection but is there any specific reason to make HashParser class as internal?

Thanks,

**Comment by ikrmkg** [comment]
will use BCrypt.Net.BCrypt.InterrogateHash

**Comment by jvandertil** [comment]
Bit late to this party, but have you considered using `BCrypt.PasswordNeedsRehash`?

Signature:
```cs
public static bool PasswordNeedsRehash(string hash, int newMinimumWorkLoad)
```
