### ISSUE TITLE
How many rounds is the default for this library?

### ISSUE THREAD

**Issue by 37devv** [BcryptNet/bcrypt.net#82]
Hi all
On this page https://bcrypt-generator.com/ there are 12 rounds of encryption.
What is the default for this library?
In the readme, there is this sentence: This implementation on hashing will generate a salt automatically for you with the work factor (2^number of rounds) set to 10
is this the cost for hashing also or only for the creation of a salt?

**Comment by ChrisMcKee** [comment]
https://github.com/BcryptNet/bcrypt.net/blob/main/src/BCrypt.Net/BCrypt.cs#L79

Default is currently 11
