### ISSUE TITLE
What is the maximum character limit that this bcrypt library can handle? 

### ISSUE THREAD

**Issue by firephantomassasin** [BcryptNet/bcrypt.net#84]
What is the maximum character limit that this bcrypt library can handle? I saw on others that it can handle up to 72 characters, or 55 characters, I am not sure with this library. I would like to know what is the maximum characters.

**Comment by ChrisMcKee** [comment]
In the case of the library 72
https://github.com/BcryptNet/bcrypt.net/blob/main/src/BCrypt.Net.UnitTests/BCryptTests.cs#L105-L112

But you can retain entropy above this with the 'enhanced hashing' functionality.

**Comment by firephantomassasin** [comment]
@ChrisMcKee  if we're gonna use the enhanced hashing, what would be the new max characters limit?

**Comment by ChrisMcKee** [comment]
Heat death of the universe or the maximum achievable entropy of SHA384 whichever comes first

**Comment by ChrisMcKee** [comment]
The enhanced hashing basically pre-hashes the key in order to avoid loss of entropy over the 72 character limit. 
Its a common implementation (rather than one pulled out of my ... head) 😄

**Comment by firephantomassasin** [comment]
Thanks @ChrisMcKee  :D this library is awesome! We will try to use this.
