### ISSUE TITLE
NuGet license URL reflects incorrect branch

### ISSUE THREAD

**Issue by AaronFeickert** [BcryptNet/bcrypt.net#90]
The license URL provided in NuGet reflects the wrong branch: `master` instead of `main`. While visiting the license link will redirect, some tools (like those used to automatically list and obtain licenses) may not be able to fetch the license correctly.

**Comment by ChrisMcKee** [comment]
Thanks; my fault. Github poked to rename it and promised to redirect the branch... 🙄

**Comment by AaronFeickert** [comment]
> Thanks; my fault. Github poked to rename it and promised to redirect the branch... 🙄

It does redirect, but I noticed that a license-fetching tool didn't handle the redirect properly.

**Comment by ChrisMcKee** [comment]
Updated the csproj files so it'll correct when it next goes out. Licence fetching tool probably needs follow-redirects setting.

**Comment by AaronFeickert** [comment]
> Updated the csproj files so it'll correct when it next goes out. Licence fetching tool probably needs follow-redirects setting.

Thanks for the quick update. Filed an issue with the license fetching tool as well, since this kind of branch redirection might be fairly common: https://github.com/tomchavakis/nuget-license/issues/60
