### ISSUE TITLE
BCrypt runs extremely slow on WinForms

### ISSUE THREAD

**Issue by MisinformedDNA** [BcryptNet/bcrypt.net#92]
I can consistently get BCrypt.HashPassword to take 20 to 30 seconds on my WinForms project.

It actually runs quite quickly on a new WinForms app using .NET Core 3.1 or even .NET Framework 4.8. But when I copy my project file from the existing WinForms project to the new project, it takes 20 to 30 seconds to complete.

Here's the CSPROJ:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <IsWebBootstrapper>true</IsWebBootstrapper>
    <!--<ApplicationIcon>..\Resources\favicon.ico</ApplicationIcon>-->
    <PublishUrl>http://localhost/NBi/</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Web</InstallFrom>
    <UpdateEnabled>true</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <DocumentationFile>bin\Debug\NBi.XML</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.configuration" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.2.0">
      <Visible>False</Visible>
      <ProductName>.NET Framework 2.0</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.2" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.DirectoryServices" Version="5.0.0" />
  </ItemGroup>
</Project>
```

and here is the [repro project](https://github.com/BcryptNet/bcrypt.net/files/6224166/WinFormsApp1.zip). Just set breakpoints on the BCrypt calls and do a step over and it should be about 20 seconds or more.

Any ideas what could be going on here?

UPDATE: It looks like all that extra project nonsense is inconsequential. The slowness happens just from switching the target frramework to `net48`.

**Comment by MisinformedDNA** [comment]
Here's the CPU usage for `BCrypt.HashPassword("password", 8)` (so it doesn't take so long):

![image](https://user-images.githubusercontent.com/1784452/112905919-ebd23d80-90b0-11eb-88d9-de8e84b148cb.png)

**Comment by ChrisMcKee** [comment]
Weird one. I'm on UK time so be tomorrow before I look properly.
In the meantime can you try V3.0.1

**Comment by ChrisMcKee** [comment]
![image](https://user-images.githubusercontent.com/83597/112981583-51770600-9153-11eb-96d9-4aba0878fd87.png)

I'm not sure what template you're using to create winform apps in the new sdk format? VS has 2 for me and both are the older project style.

**Comment by ChrisMcKee** [comment]
Guessing you used `dotnet new winforms` but I'm not sure the SDK format supports pre-v5; the tooling changes seem to cover migrating from 4x to .net 5; I'm struggling to see anything around then backporting versioning for msbuild

**Comment by ChrisMcKee** [comment]
![image](https://user-images.githubusercontent.com/83597/112983286-6ce31080-9155-11eb-8d24-10a2cdfa2829.png)
For parity; upgraded the win app to .net 5.
VS doesnt offer an option to go down to 4.8 in SDK style
![image](https://user-images.githubusercontent.com/83597/112983364-8421fe00-9155-11eb-952a-7d90205ab170.png)

**Comment by MisinformedDNA** [comment]
You are correct that VS doesn't allow you to create WinForms in 4.8, I just edited the csproj's target framework.

SDK-style is indeed [supported](https://docs.microsoft.com/en-us/dotnet/standard/frameworks) for .NET Framework. In fact, converting to SDK-style is one of the first steps in migrating to .NET Core+.

Also, the IDesignToolsClient error goes away if you unload and reload the project.

If you use the repro app I attached, are you seeing any slowness?

**Comment by ChrisMcKee** [comment]
If you look at the test https://github.com/BcryptNet/bcrypt.net/commit/cd3ee2189ecbe3becf4bdf1238c4bf7a57b54105 
its fine. You don't need to call GenerateSalt() its an internal exposed for compatibility.

I had to alter your example to 
```
            var sw = Stopwatch.StartNew();
            BCrypt.Net.BCrypt.HashPassword("changeme", BCrypt.Net.BCrypt.GenerateSalt());
            Trace.WriteLine(sw.ElapsedMilliseconds);
```

Otherwise I can't tell anythings happened; but hit run and it was fine

**Comment by ChrisMcKee** [comment]
Just to check it wasn't a "works on my machine" answer; I've copied *your* example into a few different T3 size machines (small / medium) windows boxes in aws and ran it without issue.

**Comment by MisinformedDNA** [comment]
Interesting. So it's something on my box...
