### ISSUE TITLE
Type or namespace name 'HashPassword' does not exist in the namespace BCrypt

### ISSUE THREAD

**Issue by zmagickap** [BcryptNet/bcrypt.net#99]
I read two ISSUES on this topic and a referenced stackoverflow solution. But, nothing mentioned fixed this for me.

I'm using net 5 and the current bcrypnet.

`using BCrypt.Net;`
...
`PasswordHash = BCrypt.HashPassword("my password");`

I tried the = alias suggestion but that didn't fix it.

Any help?

**Comment by iceboss3d** [comment]
Experiencing same issue also

**Comment by ChrisMcKee** [comment]
![image](https://user-images.githubusercontent.com/83597/125981257-14096431-d2ff-4908-a998-4d1366c8fd22.png)

Try moving BCrypt.Net in your name space 

Outside of the namespace in the same format Roslyn seems to show an error, pretty sure that's wonky behaviour; as this works
![image](https://user-images.githubusercontent.com/83597/125981390-16d3a46e-59f1-4e02-bb22-38a5d068d293.png)

**Comment by ChrisMcKee** [comment]
You can of course import statics ala 

```csharp
using System;
using static BCrypt.Net.BCrypt;

namespace BcryptNet5
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var hash = HashPassword("Test");
        }
    }
}

```

**Comment by zmagickap** [comment]
This is what finally worked for me. It was a bear finding an article that suggested this.
